___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Tom/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Tom/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Tom/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib',

Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [4]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [5]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [12]:
v = np.random.randint(0, 20, (20))
print(v)

[17 19 15 14  0  4 12 14  2 19  3  3  7 12  1  9 18  0 17  1]


In [13]:
nonzero = np.nonzero(v)
print(nonzero)

(array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 18,
       19], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [14]:
mean = np.mean(v)
median = np.median(v)
std = np.std(v)
print('среднее значение =', mean, 'медиана =', median, 'стандартное отклонение =', std)

среднее значение = 9.35 медиана = 10.5 стандартное отклонение = 6.894019147057832


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [27]:
A = np.random.randint(1, 10, (4, 2))
print(A, 'this is A')
B = np.random.randint(1, 10, (2, 2))
print(B, 'this is B')
product = np.dot(A, B)
print(product)

[[7 1]
 [5 6]
 [8 9]
 [6 9]] this is A
[[8 6]
 [3 5]] this is B
[[59 47]
 [58 60]
 [91 93]
 [75 81]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [32]:
vector = product.reshape(8)
print(vector)
minimum = vector.min()
maximum = vector.max()
print('min =', minimum, 'max =', maximum)
vector[np.argmax(vector)] = 0
print(vector)

[59 47 58 60 91 93 75 81]
min = 47 max = 93
[59 47 58 60 91  0 75 81]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [49]:
corr1 = np.corrcoef(product[0], product[1])
corr2 = np.corrcoef(product[0], product[2])
corr3 = np.corrcoef(product[0], product[3])
print(corr1, '- полная линейная обратная взаимосвязь')
print(corr2, '- полная линейная положительная взаимосвязь')
print(corr3, '- полная линейная обратная взаимосвязь')

[[ 1. -1.]
 [-1.  1.]] - полная линейная обратная взаимосвязь
[[1. 1.]
 [1. 1.]] - полная линейная положительная взаимосвязь
[[ 1. -1.]
 [-1.  1.]] - полная линейная обратная взаимосвязь


Дано матрицю. Знайти ранг матриці:

In [52]:
a = np.array([[1, 4, 5],
              [7, 3, 2],
              [9, 16, 1]])
rank = np.linalg.matrix_rank(a)
rank

3

Знайти визначник матриці:

In [54]:
det = np.linalg.det(a)
det

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [55]:
np.linalg.eig(a)

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
        -4.56760167-3.20389947j]),
 array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
         -0.31386258+0.47450898j],
        [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
         -0.07049527-0.4090732j ],
        [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
          0.7099444 -0.j        ]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [60]:
a = np.random.randint(0,10,50)
print(a)
np.bincount(a).argmax()

[6 7 6 1 5 0 2 1 5 4 8 4 1 3 6 2 3 9 6 3 7 6 2 3 9 7 7 1 0 3 6 6 7 7 1 5 9
 6 1 5 8 5 2 3 0 4 2 8 7 6]


6

Виведіть лише парні числа, що діляться на 5:

In [66]:
a = np.random.randint(0,10,50)
print(a, 'Ноль — чётное число')
a[(a % 2 == 0) & (a % 5 == 0)]

[6 7 5 7 9 8 9 2 2 3 9 6 3 8 9 2 1 0 6 1 8 9 8 5 4 8 6 6 9 5 8 3 2 9 0 3 2
 0 4 0 2 4 5 8 7 5 7 6 5 6] Ноль — чётное число


array([0, 0, 0, 0])

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [70]:
M = np.array([[2., 5.], [1., -10.]])
v = np.array([1., 3.])
np.linalg.solve(M, v)

array([ 1. , -0.2])